Implement sharesapiimpl with in memory persistance
agile-lab-dev/lake-sharing pull request #21
Opened 2023-09-14 16:39 UTC by duhizjame

2023-09-22 15:01 UTC, matar993 requested changes

2023-09-22 15:05 UTC, matar993 commented on server/src/test/java/io/delta/sharing/api/server/DeltaSharesApiImplTest.java
> +  }
A test without `maxResults` and `pageToken` query params is needed.

2023-09-22 15:10 UTC, matar993 commented on server/src/main/java/io/delta/sharing/api/server/DeltaSharesApiImpl.java
> +                    Optional.of(pageToken), Optional.of(maxResults.intValue()));
Also you must use `Optional.ofNullable()`

2023-09-22 15:47 UTC, duhizjame commented
@matar993 resolved comments via the latest commit

2023-09-25 17:19 UTC, tmnd1991 commented on server/src/main/java/io/delta/sharing/api/server/PagingUtils.java
> +public class PagingUtils {
Remove this

2023-09-25 17:35 UTC, tmnd1991 approved these changes

2023-09-25 17:35 UTC, merged